### ISSUE TITLE
acceptance:parallel:multibrowsers doesn't exist

### ISSUE THREAD

**Issue by lorsatti** [salesforce/codeceptjs-bdd#43]
https://gkushang.github.io/03-01-run-locally/5-run-on-multi-browsers/ cites `acceptance:parallel:multibrowsers`. This script isn't generated by `create-codeceptjs-bdd-tests`. See [update.package.js](https://github.com/salesforce/codeceptjs-bdd/blob/develop/packages/create-codeceptjs-bdd-tests/cli/update.package.js#L5)

**Comment by gkushang** [comment]
@lorsatti Thanks for fixing this issue part of https://github.com/salesforce/codeceptjs-bdd/pull/45
